config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  resources :category, only: %i(new create edit update) do
    resources :tasks, except: %i(index)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
  
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :set_category, only: %i(edit update)
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(params_category)
      redirect_to :root
    else
      render action: :edit
    end
  end

  private

  def params_category
    params.require(:category).permit(:title).merge(user: current_user)
  end

  def set_category
    @category = Category.find_by(id: params[:id])
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task , only: %i(show edit update destroy)
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def show
  end

  def edit
    @categories = Category.where(user: current_user)
  end

  def update
    if @task.update_attributes(task_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to :root
  end

  private
  def task_params
    params.require(:task).permit(:name,:memo,:category_id)
  end

  def set_task
    @task = Task.find_by(id: params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @category = Category.where(user: current_user)
    @task = Task.where(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/category/edit.html.erb
<div class="task_container">
  <h1>カテゴリーを編集する</h1>
  <%= form_with model: @category, url:{ action: :update} do |f| %>
  <div class="form_card">
      <%= f.label :title, class: 'form_label'%>
      <%= f.text_field :title, class: 'form_field' %>
  </div>
  <%= f.submit "編集する", data: { confirm: "編集してもいいですか？" } %>
  <% end %>

  <p style="margin-top:20px;"><%= link_to "topへ戻る", root_path %></p>
  
</div>

app/views/category/new.html.erb
<%= form_with model: @category, url: {action: :create},local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "登録する" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'partial/header' if current_user %>
    <%= yield %>
  </body>
</html>

app/views/partial/_header.html.erb
<section class="header">
  <h1 class="hidden">header</h1>
  <%= link_to "ToDo", root_path, class: 'logo' %>
  <div class="user_name"><%= "#{current_user.name}さん" %></div>
  <div class="header_nav">
    <ul class="nav_body">
      <li class="nav_item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</section>

app/views/tasks/edit.html.erb
<div class="task_container">
  <h1>タスクを編集する</h1>
  <%= form_with model: @task, url: {action: :update} , local: true do |f| %>
    <div class="form_card">
      <%= f.label :name, class: 'form_label'%>
      <%= f.text_field :name, class: 'form_field'%>
    </div>
    <div class="form_card">
      <%= f.label :memo, class: 'form_label' %>
      <%= f.text_area :memo, class: 'form_field' %>
    </div>
    <div class="form_selecter">
      <%= select :task, :category_id, @categories.map{ |c| [c.title, c.id] }, {}, { class: 'form-control' } %>
    </div>
    <%= f.submit "編集する" %>
  <% end %>
  <p style="margin-top:20px;"><%= link_to "topへ戻る", root_path %></p>
</div>

app/views/tasks/new.html.erb
<div class="task_container">
  <h1>タスクの新規作成</h1>
  <%= form_with model: @task, url: {action: :create} , local: true do |f| %>
  <%= f.hidden_field :category_id, value: params[:category_id] %>
    <div class="form_card">
      <%= f.label :name, class: 'form_label'%>
      <%= f.text_field :name, class: 'form_field'%>
    </div>
    <div class="form_card">
      <%= f.label :memo, class: 'form_label' %>
      <%= f.text_area :memo, class: 'form_field' %>
    </div>
    <%= f.submit "登録する" %>
  <% end %>
  <p style="margin-top:20px;"><%= link_to "topへ戻る", root_path %></p>
</div>

app/views/tasks/show.html.erb
<div class="task_container">
  <p class="task_show_name"><span>task_name:</span><%= @task.name %></p>
  <p class="task_show_memo"><span>memo:</span><%= @task.memo %></p>
  <p><%= link_to "topへ戻る", root_path %></p>
</div>

app/views/top/index.html.erb
<div class="category_container">
    <% @category.each.with_index(1) do |c, i| %>
      <%= tag.div(class: "category_area_#{i} category_area") do %>
        
          <div class="category_header">
            <p class="category_title"><%= c.title %></p>
            <%= link_to "編集する", edit_category_path(c) %>
          </div>
          <% c.tasks.each do |t| %>
            <%= link_to category_task_path(c,t), class: 'card_wrap' do %>
              <div class="task_card">
                <p class="task_card_text"><span>task:</span><%= t.name %></p>
                <%= link_to "編集", edit_category_task_path(c,t) %>
                <%= link_to "削除", category_task_path(c,t), method: :delete, data: { confirm: "#{t.name}を削除して大丈夫ですか？" } %>
              </div>
            <% end %>
          <% end %>

          <p>
            <%= link_to "taskを追加する", new_category_task_path(category_id: c.id) %>
          </p>
        <% end %>
    <% end %>
</div>